CREATE DATABASE PRODUCT;
CREATE TABLE FOOD(
ID INT PRIMARY KEY auto_increment,
 PRODUCT_NAME VARCHAR (50) NOT NULL,
 AMOUNT INT CHECK(AMOUNT> 20000),
 COUNTRY VARCHAR(50)default("NIGERIA"));
 INSERT INTO FOOD(PRODUCT_NAME,AMOUNT)
 VALUES( "APPLE",45000),
 ("LEMON",22000),
 ("PINEAPPLE",30000),
 ("BANANA",25000),
 ("PAWPAW",35000);
 SELECT * FROM FOOD
 